version: '3'

services:
  database:
    build:
      context: docker/database
    environment:
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/data:/var/lib/mysql
  php-fpm:
    build:
      context: docker/php-fpm
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ./dockler-backend:/var/www/dockler-backend
  vue-ui:
    build:
      context: ./dockler-front
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
      - ./dockler-front:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./dockler-backend:/var/www/dockler-backend
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8081:8081"
      - "443:443"


